#--------------------------------------------------------
# Copyright IBM Corp. 2020. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#--------------------------------------------------------
#
# This ClusterRole should be used in conjunction with the system:kube-scheduler
# ClusterRole to grant the scheduler the permissions it needs to operate
# 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-lsf-operator 
  labels:
    app.kubernetes.io/name: "ibm-spectrum-lsf"
    app.kubernetes.io/managed-by: "lsfclusters.lsf.spectrumcomputing.ibm.com"
    app.kubernetes.io/instance: "lsf"
    release: "lsf"
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - resourcequotas
  - nodes
  verbs:
  - list
  - update
  - get
  - watch
  - patch
  - create
- apiGroups:
  - batch
  resources:
  - "*"
  verbs:
  - list
  - update
  - get
  - watch
  - patch
  - create
- apiGroups:
  - ibm.com
  resources:
  - paralleljobs
  - resourceplans
  verbs:
  - "*"
- apiGroups:
  - ibm.com
  resources:
  - "*"
  verbs:
  - update
- apiGroups:
  - apiextensions.k8s.io
  attributeRestrictions: null
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - watch
  - get
  - list
- apiGroups:
  - security.openshift.io 
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - events
  verbs:
  - list
  - watch
  - get
  - create
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - list
  - watch
  - get
  - create
  - patch
