apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: lsfclusters.lsf.spectrumcomputing.ibm.com
  labels:
    app.kubernetes.io/name: "ibm-spectrum-lsf"
    app.kubernetes.io/managed-by: "lsfclusters.lsf.spectrumcomputing.ibm.com"
    app.kubernetes.io/instance: "lsfcrd"
    release: "lsf"
spec:
  group: lsf.spectrumcomputing.ibm.com
  names:
    kind: LSFCluster
    listKind: LSFClusterList
    plural: lsfclusters
    singular: lsfcluster
    shortNames:
    - lsfs
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
          description: "apiVersion defines the versioned schema of this representation of an object"
        kind: 
          type: string
          description: "This CRD is for the LSFCluster kind"
        metadata:
          description: "Metadata for this specific instance"
          properties:
            name:
              type: string
              description: "Name to assign to this LSF cluster"
        spec:
          description: "Contains specifications for an LSF cluster"
          properties:
            namespace:
              type: string
              description: "The namespace to deploy in"
            serviceAccount:
              type: string
              description: "The name of the service account for the LSF cluster to use to access the K8s API"
            licenseAccepted:
              type: boolean
              description: "Indicate acceptance of the licences"
            cluster:
              description: "These are cluster wide configuration parameters"
              properties:
                lsfrole:
                  type: string
                  description: "Either lsf or podscheduler"
                clustername:
                  type: string
                  description: "Prefix for objects created for this cluster"
                administrators:
                  description: "A list of LSF administrators"
                  type: array
                  items:
                    type: string
                pvc:
                  description: "Storage for failover"
                  properties:
                    dynamicStorage:
                      type: boolean
                    storageClass:
                      type: string
                    selectorLabel:
                      type: string
                    selectorValue:
                      type: string
                    size:
                      type: string
                volumes:
                  description: "List of additional volumes to mpount to all LSF pods"
                  type: array
                  items:
                    properties:
                      name:
                        type: string
                      mount:
                        type: string
                      selectorLabel:
                        type: string
                      selectorValue:
                        type: string
                      accessModes:
                        type: string
                      size:
                        type: string
                userauth:
                  description: "Configutation for providing user authentication within pods"
                  properties:
                    authconfigargs:
                      type: string
                    configs:
                      type: array
                      items:
                        properties:
                          name:
                            type: string
                          filename:
                            type: string
                    starts:
                      description: "List of daemons to start for authentication"
                      type: array
                      items:
                        type: string
            master:
              properties:
                image:
                  type: string
                imagePullPolicy:
                  type: string
                replicas:
                  type: integer
                  minimum: 0
                  maximum: 1
                placement:
                  properties:
                    includeLabel:
                      type: string
                    excludeLabel:
                      type: string
                    tolerateName:
                      type: string
                    tolerateValue:
                      type: string
                    tolerateEffect:
                      type: string
                resources:
                  properties:
                    requests:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    limits:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                mountList:
                  type: array
                  items:
                    type: string
            gui:
              properties:
                image:
                  type: string
                imagePullPolicy:
                  type: string
                replicas:
                  type: integer
                  minimum: 0
                  maximum: 1
                db:
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                    cpu:
                      type: string
                    memory:
                      type: string
                    passwordSecret:
                      type: string
                placement:
                  properties:
                    includeLabel:
                      type: string
                    excludeLabel:
                      type: string
                    tolerateName:
                      type: string
                    tolerateValue:
                      type: string
                    tolerateEffect:
                      type: string
                resources:
                  properties:
                    requests:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    limits:
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                mountList:
                  type: array
                  items:
                    type: string

            computes:
              type: array
              items:
                properties:
                  image:
                    type: string
                  imagePullPolicy:
                    type: string
                  replicas:
                    type: integer
                    minimum: 0
                    maximum: 1
                  placement:
                    properties:
                      includeLabel:
                        type: string
                      excludeLabel:
                        type: string
                      tolerateName:
                        type: string
                      tolerateValue:
                        type: string
                      tolerateEffect:
                        type: string
                  resources:
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                  mountList:
                    type: array
                    items:
                      type: string

