#--------------------------------------------------------
# Copyright IBM Corp. 2020. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#--------------------------------------------------------
#
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'this allows access to many privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is only for hpac.'
  name: ibm-lsf-scc
  labels:
    app.kubernetes.io/name: "ibm-spectrum-lsf"
    app.kubernetes.io/managed-by: "lsfclusters.lsf.spectrumcomputing.ibm.com"
    app.kubernetes.io/instance: "lsf"
    release: "lsf"
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:nodes
- system:masters
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- KILL
- SETUID
- SETGID
- CHOWN
- SETPCAP
- NET_BIND_SERVICE
- DAC_OVERRIDE
- SYS_ADMIN
- AUDIT_WRITE
- SYS_TTY_CONFIG
allowedUnsafeSysctls:
- '*'
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
- NET_RAW
- SYS_CHROOT
- SETFCAP
- AUDIT_WRITE
- FOWNER
- FSETID
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:admin
volumes:
- '*'

