# This is a template for a preemptible low priority job.
# It will start 10 pods in the "idle" queue.
# Each will run for 3600 seoonds
apiVersion: batch/v1
kind: Job
metadata:
  name: ppnp-low-SEQ
spec:
  parallelism: 10
  completions: 10
  template:
    metadata:
      name: ppnp-low-SEQ
      annotations:
        lsf.ibm.com/queue: "idle"
    spec:
      schedulerName: lsf
      containers:
      - name: sleepjob
        image: ubuntu:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep", "3600"]
        resources:
          requests:
            cpu: 1
            memory: 128M
          limits:
            cpu: 1
            memory: 128M

      restartPolicy: Never
